# Generated by Django 5.1.4 on 2024-12-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_learn', '0002_subtopic_studentprogress_subtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='C_learn.subtopic'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='C_learn.topic'),
        ),
    ]
