# Generated by Django 5.1.4 on 2024-12-28 15:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C_learn', '0003_alter_studentprogress_subtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
