# Generated by Django 5.1.4 on 2025-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C_learn', '0004_alter_subtopic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
