# Generated by Django 5.1.4 on 2025-01-22 12:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C_learn', '0005_alter_subtopic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
